/* GENERATED by tools/build-fx.py — do not edit.
 * Frame strips in assets/fx.png: r is [x, y, frameW, frameH].
 */
'use strict';
const FX_ATLAS = {
 "boom": {
  "n": 8,
  "r": [
   0,
   0,
   117,
   114
  ]
 },
 "spark": {
  "n": 4,
  "r": [
   0,
   114,
   122,
   119
  ]
 }
};
