/* GENERATED by tools/build-towers.py — do not edit.
 * Atlas rectangles for assets/towers.png: three tiers and one
 * projectile per tower type.
 */
'use strict';
const TOWER_ATLAS = {
 "arcane": {
  "shot": [
   250,
   420,
   39,
   39
  ],
  "tiers": [
   [
    257,
    0,
    162,
    190
   ],
   [
    0,
    0,
    132,
    240
   ],
   [
    132,
    0,
    125,
    240
   ]
  ]
 },
 "bolt": {
  "shot": [
   199,
   420,
   17,
   56
  ],
  "tiers": [
   [
    0,
    240,
    177,
    180
   ],
   [
    594,
    0,
    177,
    182
   ],
   [
    771,
    0,
    177,
    182
   ]
  ]
 },
 "fire": {
  "shot": [
   216,
   420,
   34,
   55
  ],
  "tiers": [
   [
    705,
    240,
    175,
    156
   ],
   [
    530,
    240,
    175,
    173
   ],
   [
    419,
    0,
    175,
    188
   ]
  ]
 },
 "ice": {
  "shot": [
   175,
   420,
   24,
   56
  ],
  "tiers": [
   [
    0,
    420,
    175,
    126
   ],
   [
    177,
    240,
    175,
    179
   ],
   [
    352,
    240,
    178,
    179
   ]
  ]
 }
};
