#!/usr/bin/env python3
"""Pack the tower tiers and projectiles from the pack into one atlas.

    python3 tools/build-towers.py ~/art/Tower_Assets_2/PNG

The pack ships each tower as THREE tiers, not one, and a projectile per
element. The game had been using one tier of each as a flat sprite — and not
even consistently: the file it called tower_arcane was tier three of the dark
tower, while tower_bolt was tier one of the temple. Matching them up is done
by exact pixel size against what the game already shipped, not by eye.

Tiers are earned: a tower's art steps up as it is upgraded, so spending on a
tower is visible on the board rather than only in the upgrade panel.

Output:
    assets/towers.png    the atlas
    towers-data.js       generated manifest — do not edit by hand
"""
import argparse, json, os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))

ap = argparse.ArgumentParser()
ap.add_argument('source', help="the pack's PNG dir of numbered tower art")
ap.add_argument('--out', default=os.path.join(ROOT, 'assets'))
a = ap.parse_args()

# type -> the pack's three tier files, then its projectile.
# Verified against the sprites the game already shipped: tower_fire was 175x156
# which is 2.png, tower_ice 175x126 is 6.png, tower_bolt 177x180 is 11.png, and
# tower_arcane 162x311 is 18.png — the THIRD tier of the dark tower.
TOWERS = {
    'fire':   {'tiers': [2, 3, 4],    'shot': 1},    # tan dome, flame orb
    'ice':    {'tiers': [6, 7, 8],    'shot': 10},   # igloo, icicle
    'bolt':   {'tiers': [11, 12, 13], 'shot': 19},   # temple, yellow bolt
    'arcane': {'tiers': [16, 17, 18], 'shot': 14},   # dark spikes, red orb
}

TOWER_CAP = 240        # the game fits a tower into a 132px box; 240 is ample
SHOT_CAP = 56          # drawn a few tens of pixels across


def grab(n, cap):
    p = os.path.join(a.source, f'{n}.png')
    if not os.path.exists(p):
        return None
    im = Image.open(p).convert('RGBA')
    b = im.getbbox()
    if b:
        im = im.crop(b)
    s = min(cap / max(im.width, im.height), 1.0)
    if s < 1.0:
        im = im.resize((max(1, round(im.width * s)), max(1, round(im.height * s))),
                       Image.LANCZOS)
    return im


cells, manifest, missing = [], {}, []
for name, spec in TOWERS.items():
    entry = {'tiers': [], 'shot': None}
    for i, n in enumerate(spec['tiers']):
        im = grab(n, TOWER_CAP)
        if im is None:
            missing.append(f'{name} tier {i+1} ({n}.png)')
            continue
        cells.append((f'tier:{name}:{i}', im))
    # Tier one also goes out as a standalone file. It is what the HUD slot
    # shows, and what the board falls back to if the atlas fails to load —
    # a tower that does not draw is worse than a tower without tiers.
    t1 = grab(spec['tiers'][0], TOWER_CAP)
    if t1 is not None:
        os.makedirs(a.out, exist_ok=True)
        q = t1.quantize(colors=256, method=Image.FASTOCTREE).convert('RGBA') \
              .quantize(colors=256, method=Image.FASTOCTREE)
        q.save(os.path.join(a.out, f'tower_{name}.png'), optimize=True)

    im = grab(spec['shot'], SHOT_CAP)
    if im is None:
        missing.append(f'{name} shot ({spec["shot"]}.png)')
    else:
        cells.append((f'shot:{name}', im))
    manifest[name] = entry

if missing:
    print('MISSING from ' + a.source + ':')
    for m in missing:
        print('  ' + m)
    if len(missing) == len(TOWERS) * 4:
        sys.exit(1)

# Shelf pack, tallest first. Runs once, offline.
cells.sort(key=lambda c: -c[1].height)
W = 1024
x = y = shelf = 0
placed = {}
for key, im in cells:
    if x + im.width > W:
        x = 0
        y += shelf
        shelf = 0
    placed[key] = [x, y, im.width, im.height]
    x += im.width
    shelf = max(shelf, im.height)
H = y + shelf

atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for key, im in cells:
    px, py, _, _ = placed[key]
    atlas.paste(im, (px, py))

for key, rect in placed.items():
    kind, rest = key.split(':', 1)
    if kind == 'shot':
        manifest[rest]['shot'] = rect
    else:
        name, idx = rest.split(':')
        while len(manifest[name]['tiers']) <= int(idx):
            manifest[name]['tiers'].append(None)
        manifest[name]['tiers'][int(idx)] = rect

os.makedirs(a.out, exist_ok=True)
atlas = atlas.quantize(colors=256, method=Image.FASTOCTREE).convert('RGBA') \
             .quantize(colors=256, method=Image.FASTOCTREE)
path = os.path.join(a.out, 'towers.png')
atlas.save(path, optimize=True)

data = os.path.join(ROOT, 'towers-data.js')
with open(data, 'w') as f:
    f.write('/* GENERATED by tools/build-towers.py — do not edit.\n'
            ' * Atlas rectangles for assets/towers.png: three tiers and one\n'
            ' * projectile per tower type.\n'
            ' */\n')
    f.write("'use strict';\nconst TOWER_ATLAS = ")
    f.write(json.dumps(manifest, indent=1, sort_keys=True))
    f.write(';\n')

print(f'atlas  {atlas.size[0]}x{atlas.size[1]}  '
      f'{os.path.getsize(path):,} bytes -> {path}')
for name in sorted(manifest):
    m = manifest[name]
    tiers = ' '.join(f'{r[2]}x{r[3]}' if r else '--' for r in m['tiers'])
    shot = f"{m['shot'][2]}x{m['shot'][3]}" if m['shot'] else '--'
    print(f'  {name:<8} tiers {tiers:<28} shot {shot}')
print(f'manifest -> {data}')
print('\nThen: python3 tools/stamp-sw.py')
