#!/usr/bin/env python3
"""Pack the pack's impact animations into one atlas.

    python3 tools/build-fx.py ~/art/Tower_11/PNG

Two sequences are used:

    boom    an eight-frame explosion, red bloom to smoke to fading ring.
            This is the arcane tower's splash, which was an expanding circle.
    spark   a four-frame spark burst, used for every projectile hit and
            tinted at load to the firing tower's colour.

Frames in a sequence are different sizes because the effect expands, and each
is centred on its own middle. They are padded to a common box rather than
trimmed to one, so the burst grows from a fixed point instead of drifting.

Output:
    assets/fx.png    the atlas
    fx-data.js       generated manifest — do not edit by hand
"""
import argparse, json, os, sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))

ap = argparse.ArgumentParser()
ap.add_argument('source')
ap.add_argument('--out', default=os.path.join(ROOT, 'assets'))
a = ap.parse_args()

SEQS = {'boom': range(54, 62), 'spark': range(36, 40)}
CAP = 128        # drawn around 90px across; more is detail nobody sees

sheets = {}
for name, rng in SEQS.items():
    ims = []
    for n in rng:
        p = os.path.join(a.source, f'{n}.png')
        if os.path.exists(p):
            ims.append(Image.open(p).convert('RGBA'))
    if not ims:
        print(f'  no frames for {name}'); continue
    # Common box = the largest frame. Each frame is centred in it: these
    # effects expand about their own centre, so centring is what keeps the
    # burst anchored.
    bw = max(i.width for i in ims)
    bh = max(i.height for i in ims)
    s = min(CAP / max(bw, bh), 1.0)
    fw, fh = max(1, round(bw * s)), max(1, round(bh * s))
    sheet = Image.new('RGBA', (fw * len(ims), fh), (0, 0, 0, 0))
    for i, im in enumerate(ims):
        box = Image.new('RGBA', (bw, bh), (0, 0, 0, 0))
        box.alpha_composite(im, ((bw - im.width) // 2, (bh - im.height) // 2))
        sheet.alpha_composite(box.resize((fw, fh), Image.LANCZOS), (i * fw, 0))
    sheets[name] = (sheet, len(ims), fw, fh)

W = max(s[0].width for s in sheets.values())
H = sum(s[0].height for s in sheets.values())
atlas = Image.new('RGBA', (W, H), (0, 0, 0, 0))
manifest, y = {}, 0
for name, (sheet, n, fw, fh) in sheets.items():
    atlas.alpha_composite(sheet, (0, y))
    manifest[name] = {'r': [0, y, fw, fh], 'n': n}
    y += sheet.height

os.makedirs(a.out, exist_ok=True)
atlas = atlas.quantize(colors=256, method=Image.FASTOCTREE).convert('RGBA') \
             .quantize(colors=256, method=Image.FASTOCTREE)
path = os.path.join(a.out, 'fx.png')
atlas.save(path, optimize=True)

data = os.path.join(ROOT, 'fx-data.js')
with open(data, 'w') as f:
    f.write('/* GENERATED by tools/build-fx.py — do not edit.\n'
            ' * Frame strips in assets/fx.png: r is [x, y, frameW, frameH].\n */\n')
    f.write("'use strict';\nconst FX_ATLAS = ")
    f.write(json.dumps(manifest, indent=1, sort_keys=True))
    f.write(';\n')

print(f'atlas  {atlas.size[0]}x{atlas.size[1]}  {os.path.getsize(path):,} bytes -> {path}')
for k in sorted(manifest):
    m = manifest[k]
    print(f"  {k:<7} {m['n']} frames  {m['r'][2]}x{m['r'][3]}")
print(f'manifest -> {data}\n\nThen: python3 tools/stamp-sw.py')
